---
# Defaults for all hosts in group 'ran_node'. Override per-host in host_vars/<hostname>.yml

# RT Ubuntu runs as root only
ansible_user: root

# Ensure POS images the RT kernel image with desired boot params
pos_image: ubuntu-jammy-rt@2025-09-11T12:59:20+00:00
pos_image_user: turletti
boot_parameters: >-
  mitigations=off usbcore.autosuspend=-1 intel_iommu=on iommu=pt selinux=0 enforcing=0
  nmi_watchdog=0 softlockup_panic=0 audit=0 skew_tick=1
  isolcpus=managed_irq,domain,0,2,4,6,8,10,12,14,16
  nohz_full=0,2,4,6,8,10,12,14,16 rcu_nocbs=0,2,4,6,8,10,12,14,16 rcu_nocb_poll
  intel_pstate=disable nosoftlockup cgroup_disable=memory mce=off
  hugepagesz=1G hugepages=40 hugepagesz=2M hugepages=0 default_hugepagesz=1G
  kthread_cpus=18-35 tsc=reliable
boot_parameters_f3: >-
  mitigations=off usbcore.autosuspend=-1 intel_iommu=on iommu=pt selinux=0 enforcing=0
  nmi_watchdog=0 softlockup_panic=0 audit=0 skew_tick=1
  isolcpus=managed_irq,domain,0,2,4,6,8,10,12,14,16
  nohz_full=0,2,4,6,8,10,12,14,16 rcu_nocbs=0,2,4,6,8,10,12,14,16 rcu_nocb_poll
  intel_pstate=disable nosoftlockup cgroup_disable=memory mce=off
  hugepagesz=1G hugepages=40 hugepagesz=2M hugepages=0 default_hugepagesz=1G
  kthread_cpus=18-35 tsc=reliable

# PTP
ptp_interface: ens15f2
ptp_domain_number: 24

# DPDK NIC and tuning
dpdk_interface: ens15f2
dpdk_max_ring_buffer_size: 8160
dpdk_mtu: 9600
dpdk_vlan: 1

# Per-host values – strongly recommended to override per host
dpdk_du_u_plane_mac: "00:11:22:33:44:66"
dpdk_du_c_plane_mac: "00:11:22:33:44:67"
dpdk_u_plane_pci: "3a:11.0"
dpdk_c_plane_pci: "3a:11.1"
dpdk_driver: "vfio-pci"

# Benetel-specific kernel boot parameters
boot_parameters_benetel: >-
  mitigations=off usbcore.autosuspend=-1 intel_iommu=on iommu=pt selinux=0 enforcing=0
  nmi_watchdog=0 softlockup_panic=0 audit=0 skew_tick=1
  isolcpus=managed_irq,domain,0,2,4,6,8,10,12,14,16
  nohz_full=0,2,4,6,8,10,12,14,16 rcu_nocbs=0,2,4,6,8,10,12,14,16 rcu_nocb_poll
  intel_pstate=disable nosoftlockup cgroup_disable=memory mce=off
  hugepagesz=1G hugepages=40 hugepagesz=2M hugepages=0 default_hugepagesz=1G
  isolcpus=managed_irq,domain,0,2,4,6,8,10,12,14 kthread_cpus=18-35
  intel_pstate=disable nosoftlockup tsc=reliable


