---
dpdk_interface: ens15f2
dpdk_max_ring_buffer_size: 8160
dpdk_mtu: 9600
dpdk_vlan: 1
dpdk_du_u_plane_mac: "00:11:22:33:44:66"
dpdk_du_c_plane_mac: "00:11:22:33:44:67"
dpdk_u_plane_pci: "3a:11.0"
dpdk_c_plane_pci: "3a:11.1"
dpdk_driver: "vfio-pci"


