---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Operator
  block:

    - name: Ensure kubectl is installed
      ansible.builtin.package:
        name: kubectl
        state: present

    - name: Ensure kustomize is installed
      ansible.builtin.package:
        name: kustomize
        state: present

    - name: Ensure cert-manager is installed
      kubernetes.core.k8s:
        state: present
        src: https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml

    - name: Create SR-IOV Operator namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: sriov-network-operator
        state: present

    - name: Clone SR-IOV Network Operator repo
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        update: yes

    - name: Deploy SR-IOV Operator using kustomize
      ansible.builtin.shell: |
        kubectl apply -k /root/sriov-network-operator/deployment/sriov-network-operator-chart
      args:
        warn: false

    - name: Wait for SR-IOV pods to be ready
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: sriov-network-operator
      register: sriov_pods
      until: sriov_pods.resources | length > 0
      retries: 10
      delay: 10

    - name: Debug SR-IOV pods
      ansible.builtin.debug:
        var: sriov_pods.resources