---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present
  become: yes

- name: Install Kustomize
  block:
    - name: Download Kustomize
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.2.0/kustomize_v5.2.0_linux_amd64.tar.gz
        dest: /tmp/kustomize.tar.gz
        mode: '0644'
        validate_certs: yes

    - name: Extract Kustomize
      ansible.builtin.unarchive:
        src: /tmp/kustomize.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        mode: '0755'

    - name: Remove Kustomize archive
      ansible.builtin.file:
        path: /tmp/kustomize.tar.gz
        state: absent
  become: yes

- name: Clone SR-IOV Network Operator repo
  ansible.builtin.git:
    repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
    dest: /root/sriov-network-operator
    version: master
    force: yes

- name: Install Go dependency for SR-IOV operator
  ansible.builtin.shell: |
    /usr/local/go/bin/go get github.com/k8snetworkplumbingwg/sriov-network-operator
  args:
    chdir: /root/sriov-network-operator

# ------------------------
# Apply CRDs individually
# ------------------------
- name: Find CRD YAML files
  ansible.builtin.find:
    paths: /root/sriov-network-operator/config/crd/bases
    patterns: "*.yaml"
    excludes: "kustomization.yaml"
    file_type: file
  register: crd_files

- name: Apply CRDs
  kubernetes.core.k8s:
    state: present
    src: "{{ item.path }}"
  loop: "{{ crd_files.files }}"

# ------------------------
# Deploy SR-IOV Operator using Kustomize
# ------------------------
- name: Build SR-IOV Operator manifests with Kustomize
  ansible.builtin.shell: |
    kustomize build /root/sriov-network-operator/deployment/sriov-network-operator-chart
  register: kustomize_output

- name: Apply SR-IOV Operator manifests
  kubernetes.core.k8s:
    state: present
    definition: "{{ kustomize_output.stdout }}"

- name: Verify deployed pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: sriov-network-operator
  register: sriov_pods

- name: Debug deployed pods
  ansible.builtin.debug:
    var: sriov_pods.resources
