---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Install and deploy SR-IOV Network Operator
  shell: |
    set -e

    # Install kubectl if missing
    if ! command -v kubectl &> /dev/null; then
      echo "Installing kubectl..."
      curl -fsSL -o /tmp/kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
      install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
    fi

    # Install kustomize if missing
    if ! command -v kustomize &> /dev/null; then
      echo "Installing kustomize..."
      curl -sLo /tmp/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.1.0/kustomize_v5.1.0_linux_amd64
      chmod +x /tmp/kustomize
      mv /tmp/kustomize /usr/local/bin/kustomize
    fi

    # Create temporary directory and clone the operator repo
    TMPDIR=$(mktemp -d)
    git clone --depth 1 https://github.com/k8snetworkplumbingwg/sriov-network-operator.git "$TMPDIR/sriov-operator"

    # Apply CRDs
    kubectl apply -k "$TMPDIR/sriov-operator/config/crd/bases"

    # Deploy the operator
    kubectl apply -k "$TMPDIR/sriov-operator/deployments"

    # Wait for operator pods to be ready
    kubectl -n sriov-network-operator wait --for=condition=Ready pod -l name=sriov-network-operator --timeout=300s

    # Cleanup
    rm -rf "$TMPDIR"
  args:
    executable: /bin/bash