---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Install dependencies and deploy SR-IOV Operator
  ansible.builtin.shell: |
    # Install kubectl if missing
    if ! command -v kubectl &> /dev/null; then
      curl -fsSL -o /tmp/kubectl https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
      install -o root -g root -m 0755 /tmp/kubectl /usr/local/bin/kubectl
    fi

    # Install kustomize if missing
    if ! command -v kustomize &> /dev/null; then
      curl -sLo /tmp/kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.1.0/kustomize_v5.1.0_linux_amd64
      chmod +x /tmp/kustomize
      mv /tmp/kustomize /usr/local/bin/kustomize
    fi

    # Deploy CRDs
    kubectl apply -f <(kustomize build /root/sriov-network-operator/config/crd/bases)

    # Deploy the SR-IOV Operator manifests
    kubectl apply -f <(kustomize build /root/sriov-network-operator/config/default)
  args:
    executable: /bin/bash