---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- block:
    - name: Ensure build dependencies are installed
      ansible.builtin.apt:
        name:
          - git
          - make
          - golang-go
        state: present
        update_cache: yes
      become: true

    - name: Clone sriov-network-operator repo
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /tmp/sriov-operator
        version: master
        force: true

    - name: Run make deploy-setup
      ansible.builtin.command:
        cmd: make deploy-setup
        chdir: /tmp/sriov-operator
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "{{ ansible_env.HOME }}/go"
      changed_when: true

    - name: Run make deploy-operator
      ansible.builtin.command:
        cmd: make deploy-operator
        chdir: /tmp/sriov-operator
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "{{ ansible_env.HOME }}/go"
      changed_when: true

    - name: Wait for SR-IOV operator to be ready
      ansible.builtin.command:
        cmd: kubectl -n sriov-network-operator wait --for=condition=Available deployment/sriov-network-operator --timeout=300s
      changed_when: false

  delegate_to: "{{ groups['ran_node'][0] }}"