---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Network Operator
  block:

    - name: Ensure required tools are installed
      apt:
        name:
          - git
          - curl
          - wget
          - kubectl
        state: present
        update_cache: yes
      become: true

    - name: Download Kustomize binary
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.5.0/kustomize_v5.5.0_linux_amd64.tar.gz
        dest: /tmp/kustomize.tar.gz
        mode: '0755'

    - name: Extract Kustomize
      ansible.builtin.unarchive:
        src: /tmp/kustomize.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]
      become: true

    - name: Clone SR-IOV Network Operator repository
      git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        version: master
        force: yes

    - name: Apply SR-IOV CRDs
      command: >
        kubectl apply -f /root/sriov-network-operator/config/crd/bases
      become: true

    - name: Deploy SR-IOV Operator via Kustomize
      command: >
        kustomize build /root/sriov-network-operator/deployment/sriov-network-operator-chart | kubectl apply -f -
      become: true

    - name: Verify SR-IOV Operator Pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: sriov-network-operator
      register: sriov_pods

    - name: Show deployed pods
      debug:
        var: sriov_pods.resources