---
- name: Deploy SR-IOV Network Operator
  block:
    - name: Install Go
      include_role:
        name: gantsign.golang
      vars:
        golang_version: "1.24.6"
        golang_install_system_wide: true
        golang_manage_gopath: false
        golang_cleanup_archive: true
      become: yes

    - name: Install git (if not already installed)
      ansible.builtin.package:
        name: git
        state: present   

    - name: Clone SR-IOV Network Operator
      ansible.builtin.git:
        repo: https://github.com/openshift/sriov-network-operator.git
        dest: /root/sriov-network-operator
        version: main

    - name: Install Go dependency for sriov-network-operator
      ansible.builtin.shell: |
        /usr/local/go/bin/go get github.com/k8snetworkplumbingwg/sriov-network-operator
      args:
        chdir: /root/sriov-network-operator

    - name: Ensure cert-manager is installed
      kubernetes.core.k8s:
        state: present
        src: https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml

    - name: Create namespace sriov-network-operator
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: sriov-network-operator
        state: present

    - name: Apply Issuer and Certificates
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: sriov-network-operator-selfsigned-issuer
            namespace: sriov-network-operator
          spec:
            selfSigned: {}
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: operator-webhook-cert
            namespace: sriov-network-operator
          spec:
            secretName: operator-webhook-cert
            dnsNames:
            - operator-webhook-service.sriov-network-operator.svc
            issuerRef:
              name: sriov-network-operator-selfsigned-issuer
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: network-resources-injector-cert
            namespace: sriov-network-operator
          spec:
            secretName: network-resources-injector-cert
            dnsNames:
            - network-resources-injector-service.sriov-network-operator.svc
            issuerRef:
              name: sriov-network-operator-selfsigned-issuer

    - name: Deploy SR-IOV Operator via Make
      ansible.builtin.shell: |
        export ADMISSION_CONTROLLERS_ENABLED=true
        export ADMISSION_CONTROLLERS_CERTIFICATES_CERT_MANAGER_ENABLED=true
        make deploy-setup-k8s
      args:
        chdir: /root/sriov-network-operator

- name: Verify SR-IOV Network Operator deployment
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: sriov-network-operator
  register: sriov_pods

- name: Debug deployed pods
  ansible.builtin.debug:
    var: sriov_pods.resources


