---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Operator
  block:
    - name: Ensure kubectl is installed
      ansible.builtin.apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Ensure kustomize is installed
      ansible.builtin.shell: |
        curl -sLo /usr/local/bin/kustomize https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_5.1.1_linux_amd64
        chmod +x /usr/local/bin/kustomize
      args:
        creates: /usr/local/bin/kustomize

    - name: Ensure skopeo is installed
      ansible.builtin.apt:
        name: skopeo
        state: present
        update_cache: yes

    - name: Apply SR-IOV CRDs
      ansible.builtin.shell: kubectl apply -f /root/sriov-network-operator/config/crd/bases
      args:
        executable: /bin/bash

    - name: Deploy SR-IOV Operator manifests via kustomize
      ansible.builtin.shell: kustomize build /root/sriov-network-operator/config/default | kubectl apply -f -
      args:
        executable: /bin/bash