---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- block:
    - name: Ensure build dependencies are installed
      ansible.builtin.apt:
        name:
          - git
          - make
          - wget
          - tar
        state: present
        update_cache: yes
      become: true

    - name: Download Go 1.23.2 tarball
      ansible.builtin.get_url:
        url: https://go.dev/dl/go1.23.2.linux-amd64.tar.gz
        dest: /tmp/go1.23.2.linux-amd64.tar.gz
        mode: '0644'

    - name: Remove old Go installation if exists
      ansible.builtin.file:
        path: /usr/local/go
        state: absent
      become: true

    - name: Install Go 1.23.2
      ansible.builtin.unarchive:
        src: /tmp/go1.23.2.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: true
      become: true

    - name: Add Go to PATH for all users
      ansible.builtin.copy:
        dest: /etc/profile.d/go.sh
        content: |
          export PATH=/usr/local/go/bin:$PATH
          export GOPATH=$HOME/go
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Clone sriov-network-operator repo
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /tmp/sriov-operator
        version: master
        force: true

    - name: Run make deploy-setup
      ansible.builtin.command:
        cmd: make deploy-setup
        chdir: /tmp/sriov-operator
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "{{ ansible_env.HOME }}/go"
      changed_when: true

    - name: Run make deploy-operator
      ansible.builtin.command:
        cmd: make deploy-operator
        chdir: /tmp/sriov-operator
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        GOPATH: "{{ ansible_env.HOME }}/go"
      changed_when: true

    - name: Wait for SR-IOV operator to be ready
      ansible.builtin.command:
        cmd: kubectl -n sriov-network-operator wait --for=condition=Available deployment/sriov-network-operator --timeout=300s
      changed_when: false

  delegate_to: "{{ groups['ran_node'][0] }}"