---
- name: Create sriov-network-operator namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: sriov-network-operator

- name: Deploy Operator Lifecycle Manager (OLM) OperatorGroup
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: sriov-network-operators
        namespace: sriov-network-operator
      spec: {}

- name: Deploy SR-IOV Network Operator subscription
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: sriov-network-operator-sub
        namespace: sriov-network-operator
      spec:
        channel: stable
        name: sriov-network-operator
        source: certified-operators
        sourceNamespace: openshift-marketplace
