---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Operator on Ubuntu 22.04
  hosts: all
  become: yes
  tasks:

    - name: Ensure kubectl is installed
      ansible.builtin.shell: |
        if ! command -v kubectl >/dev/null 2>&1; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        fi
      args:
        _uses_shell: yes

    - name: Ensure kustomize is installed
      ansible.builtin.shell: |
        if ! command -v kustomize >/dev/null 2>&1; then
          curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.1.1/kustomize_v5.1.1_linux_amd64.tar.gz
          tar -xzf kustomize.tar.gz
          install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
          rm kustomize kustomize.tar.gz
        fi
      args:
        _uses_shell: yes

    - name: Ensure Go is installed (for building operator)
      ansible.builtin.shell: |
        if ! command -v go >/dev/null 2>&1; then
          curl -LO https://dl.google.com/go/go1.24.6.linux-amd64.tar.gz
          rm -rf /usr/local/go
          tar -C /usr/local -xzf go1.24.6.linux-amd64.tar.gz
          rm go1.24.6.linux-amd64.tar.gz
        fi
      args:
        _uses_shell: yes

    - name: Clone SR-IOV Network Operator
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        clone: yes
        update: yes
        version: master

    - name: Apply SR-IOV Operator CRDs
      kubernetes.core.k8s:
        state: present
        src: /root/sriov-network-operator/config/crd/bases

    - name: Deploy SR-IOV Operator
      ansible.builtin.shell: |
        export ADMISSION_CONTROLLERS_ENABLED=true
        export ADMISSION_CONTROLLERS_CERTIFICATES_CERT_MANAGER_ENABLED=true
        make deploy-setup-k8s
      args:
        chdir: /root/sriov-network-operator
        _uses_shell: yes

    - name: Verify deployed SR-IOV Operator pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: sriov-network-operator
      register: sriov_pods

    - name: Show SR-IOV Operator pods
      ansible.builtin.debug:
        var: sriov_pods.resources