---
- name: RESTART_HERE
  ansible.builtin.meta: noop

---
- name: Ensure required packages are installed
  apt:
    name:
      - wget
      - tar
      - curl
      - git
      - make
      - gcc
      - build-essential
    state: present
    update_cache: yes

- name: Install Go 1.23
  shell: |
    wget -q https://go.dev/dl/go1.23.linux-amd64.tar.gz -O /tmp/go1.23.linux-amd64.tar.gz
    rm -rf /usr/local/go
    tar -C /usr/local -xzf /tmp/go1.23.linux-amd64.tar.gz
    ln -sf /usr/local/go/bin/go /usr/local/bin/go
  args:
    creates: /usr/local/go/bin/go
  become: true

- name: Ensure Go is in PATH for all users
  lineinfile:
    path: /etc/profile.d/go.sh
    line: 'export PATH=$PATH:/usr/local/go/bin'
    create: yes
  become: true

- name: Verify Go installation
  command: go version
  register: go_version
  changed_when: false

- name: Install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x kubectl
    mv kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl
  become: true

- name: Clone SR-IOV Operator repository
  git:
    repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
    dest: /tmp/sriov-operator
    version: main
    update: yes

- name: Fix go.mod Go version
  shell: sed -i 's/go 1.23.0/go 1.23/' /tmp/sriov-operator/go.mod
  args:
    chdir: /tmp/sriov-operator

- name: Deploy SR-IOV Operator on Kubernetes
  shell: |
    export CLUSTER_TYPE=kubernetes
    export NAMESPACE=sriov-network-operator
    make deploy-setup
  args:
    chdir: /tmp/sriov-operator
    executable: /bin/bash
  become: true