---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- block:
    - name: Check if kubectl is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/kubectl
      register: kubectl_bin

    - name: Ensure kubectl is installed
      ansible.builtin.get_url:
        url: "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
      become: true
      when: not kubectl_bin.stat.exists

    - name: Check if kustomize is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/kustomize
      register: kustomize_bin

    - name: Ensure kustomize is installed
      ansible.builtin.get_url:
        url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v5.1.0/kustomize_v5.1.0_linux_amd64"
        dest: /usr/local/bin/kustomize
        mode: '0755'
      become: true
      when: not kustomize_bin.stat.exists

    - name: Clone sriov-network-operator repo
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /tmp/sriov-operator
        version: master
        depth: 1

    - name: Apply CRDs
      ansible.builtin.command:
        cmd: kubectl apply -k /tmp/sriov-operator/config/crd/bases

    - name: Deploy SR-IOV operator
      ansible.builtin.command:
        cmd: kubectl apply -k /tmp/sriov-operator/deployment/sriov-network-operator

    - name: Wait for SR-IOV operator pod
      ansible.builtin.command:
        cmd: kubectl -n sriov-network-operator wait --for=condition=Ready pod -l name=sriov-network-operator --timeout=300s
  delegate_to: "{{ groups['ran_node'][0] }}"