---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Operator on Ubuntu 22.04
  block:

    - name: Ensure kubectl is installed
      ansible.builtin.shell: |
        if ! command -v kubectl >/dev/null 2>&1; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        fi
      args:
        _uses_shell: yes

    - name: Ensure kustomize is installed
      ansible.builtin.shell: |
        if ! command -v kustomize >/dev/null 2>&1; then
          curl -LO https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64.tar.gz
          tar -xzf kustomize_linux_amd64.tar.gz
          install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
        fi
      args:
        _uses_shell: yes

    - name: Clone SR-IOV Network Operator
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        clone: yes
        update: yes
        version: master

    - name: Deploy SR-IOV Operator using Make
      ansible.builtin.shell: |
        export ADMISSION_CONTROLLERS_ENABLED=true
        export ADMISSION_CONTROLLERS_CERTIFICATES_CERT_MANAGER_ENABLED=true
        make deploy-setup-k8s
      args:
        chdir: /root/sriov-network-operator
        _uses_shell: yes

    - name: Verify SR-IOV Operator pods
      ansible.builtin.shell: |
        kubectl get pods -n sriov-network-operator -o wide
      register: sriov_pods
      args:
        _uses_shell: yes

    - name: Show deployed SR-IOV pods
      ansible.builtin.debug:
        var: sriov_pods.stdout_lines