---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Operator (robust)
  block:
    - name: Ensure kubectl is installed
      ansible.builtin.shell: |
        if ! command -v kubectl >/dev/null; then
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        fi
      args:
        executable: /bin/bash
      become: true

    - name: Ensure kustomize is installed
      ansible.builtin.shell: |
        if ! command -v kustomize >/dev/null; then
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
        fi
      args:
        executable: /bin/bash
      become: true

    - name: Clone SR-IOV Operator repository
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        version: master
        update: yes

    - name: Apply SR-IOV CRDs individually
      ansible.builtin.shell: |
        for f in /root/sriov-network-operator/config/crd/bases/*.yaml; do
          kubectl apply -f "$f"
        done
      args:
        executable: /bin/bash
      become: true

    - name: Deploy SR-IOV Operator manifests via kustomize
      ansible.builtin.shell: |
        kustomize build /root/sriov-network-operator/deployment/sriov-network-operator | kubectl apply -f -
      args:
        executable: /bin/bash
      become: true

    - name: Verify SR-IOV pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: sriov-network-operator
      register: sriov_pods

    - name: Debug SR-IOV pods
      ansible.builtin.debug:
        var: sriov_pods.resources