---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

# -------------------------------
# Setup SR-IOV Network Operator
# -------------------------------
- name: Ensure git is installed
  ansible.builtin.package:
    name: git
    state: present

- name: Clone SR-IOV Network Operator repository
  ansible.builtin.git:
    repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
    dest: /root/sriov-network-operator
    version: master
    update: yes

- name: Install Go dependency for sriov-network-operator
  ansible.builtin.shell: |
    /usr/local/go/bin/go get github.com/k8snetworkplumbingwg/sriov-network-operator
  args:
    chdir: /root/sriov-network-operator

- name: Ensure cert-manager is installed
  kubernetes.core.k8s:
    state: present
    src: https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml

- name: Wait for cert-manager to be ready
  pause:
    seconds: 10

- name: Create sriov-network-operator namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: sriov-network-operator
    state: present

- name: Wait for namespace creation
  pause:
    seconds: 5

- name: Apply CRDs individually (exclude kustomization.yaml)
  find:
    paths: /root/sriov-network-operator/config/crd/bases
    patterns: "*.yaml"
    excludes: "kustomization.yaml"
    file_type: file
  register: crd_yaml_files

- name: Apply each CRD YAML
  kubernetes.core.k8s:
    state: present
    src: "{{ item.path }}"
  loop: "{{ crd_yaml_files.files }}"
  loop_control:
    label: "{{ item.path }}"

- name: Apply SR-IOV Network Operator manifests
  kubernetes.core.k8s:
    state: present
    src: /root/sriov-network-operator/deployment/sriov-network-operator-chart
