---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Network Operator
  block:

    - name: Ensure required packages
      apt:
        name:
          - git
          - curl
          - wget
          - build-essential
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Download Go
      get_url:
        url: "https://dl.google.com/go/go1.24.6.linux-amd64.tar.gz"
        dest: /tmp/go1.24.6.linux-amd64.tar.gz
        mode: '0644'

    - name: Extract Go to /usr/local
      unarchive:
        src: /tmp/go1.24.6.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: yes
        creates: /usr/local/go

    - name: Create GOPATH directory
      file:
        path: /opt/gopath
        state: directory
        mode: '0755'

    - name: Set up Go environment
      copy:
        content: |
          export GOROOT=/usr/local/go
          export GOPATH=/opt/gopath
          export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        dest: /etc/profile.d/golang.sh
        mode: '0755'

    - name: Symlink go binary
      file:
        src: /usr/local/go/bin/go
        dest: /usr/local/bin/go
        state: link

    - name: Clean up Go tarball
      file:
        path: /tmp/go1.24.6.linux-amd64.tar.gz
        state: absent

    - name: Clone SR-IOV Network Operator repository
      git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        clone: yes
        update: yes
        version: master

    - name: Install Go dependency for SR-IOV operator
      shell: /usr/local/go/bin/go get github.com/k8snetworkplumbingwg/sriov-network-operator
      args:
        chdir: /root/sriov-network-operator

    - name: Apply CRDs individually
      find:
        paths: /root/sriov-network-operator/config/crd/bases
        patterns: "*.yaml"
        file_type: file
      register: crd_files

    - name: Apply each CRD
      kubernetes.core.k8s:
        state: present
        src: "{{ item.path }}"
      loop: "{{ crd_files.files }}"

    - name: Create namespace sriov-network-operator
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: sriov-network-operator
        state: present

    - name: Ensure cert-manager is installed
      kubernetes.core.k8s:
        state: present
        src: https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml

    - name: Wait for 15 seconds
      pause:
        seconds: 15

    - name: Apply Issuer and Certificates
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: sriov-network-operator-selfsigned-issuer
            namespace: sriov-network-operator
          spec:
            selfSigned: {}
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: operator-webhook-cert
            namespace: sriov-network-operator
          spec:
            secretName: operator-webhook-cert
            dnsNames:
            - operator-webhook-service.sriov-network-operator.svc
            issuerRef:
              name: sriov-network-operator-selfsigned-issuer
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: network-resources-injector-cert
            namespace: sriov-network-operator
          spec:
            secretName: network-resources-injector-cert
            dnsNames:
            - network-resources-injector-service.sriov-network-operator.svc
            issuerRef:
              name: sriov-network-operator-selfsigned-issuer

    - name: Wait for 15 seconds
      pause:
        seconds: 15

    - name: Deploy SR-IOV Operator via Make
      shell: |
        export ADMISSION_CONTROLLERS_ENABLED=true
        export ADMISSION_CONTROLLERS_CERTIFICATES_CERT_MANAGER_ENABLED=true
        make deploy-setup-k8s
      args:
        chdir: /root/sriov-network-operator

    - name: Verify SR-IOV Operator pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: sriov-network-operator
      register: sriov_pods

    - name: Debug deployed pods
      debug:
        var: sriov_pods.resources