---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Deploy SR-IOV Network Operator (fixed)
  block:
    # Ensure git is installed
    - name: Install git
      ansible.builtin.package:
        name: git
        state: present

    # Clone the operator repo
    - name: Clone SR-IOV Network Operator
      ansible.builtin.git:
        repo: https://github.com/k8snetworkplumbingwg/sriov-network-operator.git
        dest: /root/sriov-network-operator
        update: yes
        version: master

    # Install Go dependency for the operator
    - name: Install Go dependency for SR-IOV operator
      ansible.builtin.shell: |
        /usr/local/go/bin/go get github.com/k8snetworkplumbingwg/sriov-network-operator
      args:
        chdir: /root/sriov-network-operator

    # Ensure cert-manager is installed
    - name: Install cert-manager
      kubernetes.core.k8s:
        state: present
        src: https://github.com/jetstack/cert-manager/releases/download/v1.3.0/cert-manager.yaml

    - name: Wait for cert-manager to be ready
      pause:
        seconds: 10

    # Create operator namespace
    - name: Create namespace sriov-network-operator
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: sriov-network-operator
        state: present

    - name: Wait for namespace creation
      pause:
        seconds: 5

    # Apply Issuer and Certificates
    - name: Apply self-signed issuer and operator certificates
      kubernetes.core.k8s:
        state: present
        definition: |
          apiVersion: cert-manager.io/v1
          kind: Issuer
          metadata:
            name: sriov-network-operator-selfsigned-issuer
            namespace: sriov-network-operator
          spec:
            selfSigned: {}
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: operator-webhook-cert
            namespace: sriov-network-operator
          spec:
            secretName: operator-webhook-cert
            dnsNames:
            - operator-webhook-service.sriov-network-operator.svc
            issuerRef:
              name: sriov-network-operator-selfsigned-issuer
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: network-resources-injector-cert
            namespace: sriov-network-operator
          spec:
            secretName: network-resources-injector-cert
            dnsNames:
            - network-resources-injector-service.sriov-network-operator.svc
            issuerRef:
              name: sriov-network-operator-selfsigned-issuer

    - name: Wait for certificates to be ready
      pause:
        seconds: 15

    # Apply all CRDs individually (skip kustomization.yaml)
    - name: Find CRDs
      find:
        paths: /root/sriov-network-operator/config/crd/bases
        patterns: "*.yaml"
        excludes: "kustomization.yaml"
        file_type: file
      register: crd_files

    - name: Apply CRDs
      kubernetes.core.k8s:
        state: present
        src: "{{ item.path }}"
      loop: "{{ crd_files.files }}"
      loop_control:
        label: "{{ item.path }}"

    # Deploy the operator manifests
    - name: Apply SR-IOV Network Operator manifests
      kubernetes.core.k8s:
        state: present
        src: /root/sriov-network-operator/deployment/sriov-network-operator-chart
