---
- name: Deploy SR-IOV Network Operator via OLM
  block:
    # 1. Install OLM CRDs and components
    - name: Install OLM CRDs
      kubernetes.core.k8s:
        state: present
        src: "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/crds.yaml"

    - name: Install OLM components
      kubernetes.core.k8s:
        state: present
        src: "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.28.0/olm.yaml"

    # 2. Wait for OperatorGroup CRD
    - name: Wait for OperatorGroup CRD to be available
      kubernetes.core.k8s_info:
        api_version: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        name: operatorgroups.operators.coreos.com
      register: crd_status
      until: crd_status.resources | length > 0
      retries: 20
      delay: 10

    # 3. Create SR-IOV Operator namespace
    - name: Ensure SR-IOV namespace exists
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-sriov-network-operator

    # 4. Deploy OperatorGroup
    - name: Create SR-IOV OperatorGroup
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: sriov-network-operator-group
            namespace: openshift-sriov-network-operator
          spec:
            targetNamespaces:
              - openshift-sriov-network-operator

    # 5. Subscribe to SR-IOV Operator
    - name: Subscribe to SR-IOV Network Operator
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: sriov-network-operator-sub
            namespace: openshift-sriov-network-operator
          spec:
            channel: stable
            name: sriov-network-operator
            source: operatorhubio-catalog
            sourceNamespace: olm