---
- name: RESTART_HERE
  ansible.builtin.meta: noop

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true

- name: Ensure required packages are installed
  apt:
    name:
      - curl
      - ca-certificates
      - apt-transport-https
      - git
    state: present
    update_cache: yes
  become: yes

- name: Ensure kubectl is installed
  ansible.builtin.shell: |
    if ! command -v kubectl > /dev/null; then
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    fi
  args:
    warn: false
  become: yes

- name: Ensure kustomize is installed
  ansible.builtin.shell: |
    if ! command -v kustomize > /dev/null; then
      curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64.tar.gz
      tar -xzf kustomize.tar.gz
      install -o root -g root -m 0755 kustomize /usr/local/bin/kustomize
      rm kustomize kustomize.tar.gz
    fi
  args:
    warn: false
  become: yes

- name: Create sriov-network-operator namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: sriov-network-operator
    state: present

- name: Deploy SR-IOV Operator
  ansible.builtin.shell: |
    git clone https://github.com/k8snetworkplumbingwg/sriov-network-operator.git /tmp/sriov-network-operator --depth 1
    kubectl apply -k /tmp/sriov-network-operator/deployment/sriov-network-operator-chart
  args:
    warn: false

- name: Wait for SR-IOV Operator pods to be running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: sriov-network-operator
  register: sriov_pods
  until: sriov_pods.resources | selectattr('status.phase', 'equalto', 'Running') | list | length > 0
  retries: 10
  delay: 10

- name: Show SR-IOV Operator pods
  ansible.builtin.debug:
    var: sriov_pods.resources