---
- name: Upload kubeadm config to the master node
  copy:
    src: kubeadm-config.yaml
    dest: /root/kubeadm-config.yaml
    mode: '0644'
  become: true

- name: Initialize Kubernetes cluster with kubeadm config
  command: kubeadm init --config kubeadm-config.yaml
  register: kubeadm_init
  failed_when: kubeadm_init.rc != 0
  changed_when: kubeadm_init.rc == 0

- name: Create .kube directory in user's home
  file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    mode: '0700'

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: yes
    mode: '0600'

- name: Wait 10 seconds for cluster to be ready
  pause:
    seconds: 10

- name: Remove NoSchedule taint from master node
  command: kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule-
  register: taint_out
  failed_when: false

- name: Extract kubeadm join command
  shell: |
    kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Set join command as fact on master host
  set_fact:
    kubeadm_join_command: "{{ join_command.stdout }}"