---
- name: (POS) Free any existing allocation for {{ node }}
  shell: pos allocations free -k "{{ node }}"

- name: (POS) Allocate {{ node }} 
  shell: pos allocations allocate "{{ node }}"

- name: (POS) Resolve POS image variables for {{ node }}
  ansible.builtin.set_fact:
    resolved_pos_image_user: "{{ hostvars[node].pos_image_user | default(pos_image_user | default('')) }}"
    resolved_pos_image: "{{ hostvars[node].pos_image | default(pos_image | default(pos_image_default)) }}"

- name: (POS) Compute imaging command for {{ node }}
  ansible.builtin.set_fact:
    pos_image_cmd: >-
      {{
        (
          'pos node image --user ' ~ resolved_pos_image_user ~ ' ' ~ node ~ ' ' ~ resolved_pos_image
        )
        if (resolved_pos_image_user is defined and (resolved_pos_image_user | length) > 0)
        else (
          'pos nodes image --staging ' ~ node ~ ' ' ~ resolved_pos_image
        )
      }}

- name: (POS) Show imaging command
  ansible.builtin.debug:
    msg: "{{ pos_image_cmd }}"

- name: (POS) Flash image to {{ node }}
  shell: "{{ pos_image_cmd }}"

- name: (POS) Set boot parameters on {{ node }} for RRU {{ hostvars[groups['faraday'][0]].rru }}
  shell: >
    pos nodes bootparameter {{ node }} {{ boot_parameters }}
  when: node == groups['ran_node'][0] and (rru | default(hostvars[groups['faraday'][0]].rru)) in ['jaguar'] and node in ['sopnode-f1', 'sopnode-f2']

- name: (POS) Set boot parameters on sopnode-f3 for RRU {{ hostvars[groups['faraday'][0]].rru }}
  shell: >
    pos nodes bootparameter {{ node }} {{ boot_parameters_f3 }}
  when: node == groups['ran_node'][0] and (rru | default(hostvars[groups['faraday'][0]].rru)) in ['jaguar'] and node in ['sopnode-f3']

- name: (POS) Reset {{ node }}
  shell: pos nodes reset "{{ node }}"

- name: (POS) Wait for SSH to be available on {{ node }}
  wait_for:
    host: "{{ node }}"
    port: 22
    timeout: 300
