---
- name: (POS) Free any existing allocation for {{ node }}
  shell: pos allocations free -k "{{ node }}"

- name: (POS) Allocate {{ node }} 
  shell: pos allocations allocate "{{ node }}"

- name: (POS) Flash image to {{ node }}
  shell: >
    {{ 'pos node image --user ' ~ pos_image_user ~ ' ' ~ node ~ ' ' ~ pos_image if pos_image_user | length > 0 else 'pos nodes image --staging ' ~ node ~ ' ' ~ pos_image }}

- name: (POS) Set boot parameters on {{ node }} for RRU {{ hostvars[groups['faraday'][0]].rru }}
  shell: >
    pos nodes bootparameter {{ node }} {{ boot_parameters }}
  when: node == groups['ran_node'][0] and (rru | default(hostvars[groups['faraday'][0]].rru)) in ['jaguar'] and node in ['sopnode-f1', 'sopnode-f2']

- name: (POS) Set boot parameters on sopnode-f3 for RRU {{ hostvars[groups['faraday'][0]].rru }}
  shell: >
    pos nodes bootparameter {{ node }} {{ boot_parameters_f3 }}
  when: node == groups['ran_node'][0] and (rru | default(hostvars[groups['faraday'][0]].rru)) in ['jaguar'] and node in ['sopnode-f3']

- name: (POS) Reset {{ node }}
  shell: pos nodes reset "{{ node }}"

- name: (POS) Wait for SSH to be available on {{ node }}
  wait_for:
    host: "{{ node }}"
    port: 22
    timeout: 300
