---
- name: Read kubeadm join command from file
  slurp:
    src: "./kubeadm_join_command.txt"
  delegate_to: localhost
  run_once: true
  register: join_file
  become: false
  
- name: Set kubeadm join command fact for all nodes
  set_fact:
    kubeadm_join_command: "{{ join_file['content'] | b64decode | trim }}"

- name: Join the node to the cluster
  command: "{{ hostvars[groups['core_node'][0]].kubeadm_join_command }} --ignore-preflight-errors=SystemVerification --v=5"

- name: Create .kube directory on worker node
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Fetch admin.conf from master to control machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./admin.conf
    flat: yes
  delegate_to: "{{ groups['core_node'][0] }}"
  when: inventory_hostname == groups['k8s_workers'][0] # avoid checksum conflict error

- name: Copy admin.conf from control machine to worker node
  copy:
    src: ./admin.conf
    dest: /root/.kube/config
    mode: '0644'
    force: yes
  become: true

- name: Wait for kubelet to start and become active
  systemd:
    name: kubelet
    state: started
    enabled: yes
