---
- name: Detect cgroup version
  command: stat -fc %T /sys/fs/cgroup
  register: cgroup_fs_type
  changed_when: false

- name: Debug cgroup version
  debug:
    msg: "This node is using {{ 'cgroup v2 (unified)' if cgroup_fs_type.stdout == 'cgroup2fs' else 'cgroup v1' }}"

- block:
    - name: Ensure kubelet config directory exists
      file:
        path: /var/lib/kubelet
        state: directory
        mode: 0755

    - name: Configure kubelet to use systemd cgroup driver
      copy:
        dest: /var/lib/kubelet/config.yaml
        content: |
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          cgroupDriver: systemd
        owner: root
        group: root
        mode: 0644

    - name: Ensure kubelet systemd drop-in directory exists
      file:
        path: /etc/systemd/system/kubelet.service.d
        state: directory
        mode: 0755

    - name: Remove legacy cgroup-driver overrides from kubelet systemd unit
      lineinfile:
        path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        regexp: '--cgroup-driver='
        state: absent

    - name: Reload systemd daemon
      command: systemctl daemon-reload
      become: true

    - name: Restart kubelet immediately
      systemd:
        name: kubelet
        state: restarted
        enabled: true

  when: cgroup_fs_type.stdout == "cgroup2fs"

- name: Join the node to the cluster
  command: "{{ hostvars[groups['core_node'][0]].kubeadm_join_command }} --v=5"

- name: Create .kube directory on worker node
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Fetch admin.conf from master to control machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./admin.conf
    flat: yes
  delegate_to: "{{ groups['core_node'][0] }}"
  when: inventory_hostname == groups['k8s_workers'][0] # avoid checksum conflict error

- name: Copy admin.conf from control machine to worker node
  copy:
    src: ./admin.conf
    dest: /root/.kube/config
    mode: '0644'
    force: yes
  become: true

- name: Wait for kubelet to start and become active
  systemd:
    name: kubelet
    state: started
    enabled: yes
