---
- name: Read join command from file
  set_fact:
    kubeadm_join_command: "{{ lookup('file', '/tmp/kubeadm_join_command.txt') }}"
  run_once: true
  delegate_to: localhost
  delegate_facts: true

- name: Join the node to the cluster
  command: "{{ kubeadm_join_command }} --ignore-preflight-errors=SystemVerification --v=5"
  when: inventory_hostname in groups['k8s_workers']

- name: Create .kube directory on worker node
  file:
    path: /root/.kube
    state: directory
    mode: '0755'

- name: Fetch admin.conf from master to control machine
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./admin.conf
    flat: yes
  delegate_to: "{{ groups['core_node'][0] }}"
  when: inventory_hostname == groups['k8s_workers'][0] # avoid checksum conflict error

- name: Copy admin.conf from control machine to worker node
  copy:
    src: ./admin.conf
    dest: /root/.kube/config
    mode: '0644'
    force: yes
  become: true

- name: Wait for kubelet to start and become active
  systemd:
    name: kubelet
    state: started
    enabled: yes
