# Namespace where the SR-IOV operator will run
sriov_namespace: sriov-network-operator

# Repo branch or tag to install from
sriov_operator_repo: "https://raw.githubusercontent.com/k8snetworkplumbingwg/sriov-network-operator/master"

# Example SR-IOV node policy
sriov_node_policy:
  name: example-policy
  resourceName: sriov_resource
  numVfs: 4
  nicVendor: "8086"   # Intel NIC vendor ID
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"