---
- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Ensure Python Kubernetes client is there to install flannel
  ansible.builtin.pip:
    name: kubernetes
    executable: pip3

- name: Create kube-flannel namespace 
  kubernetes.core.k8s:
    name: kube-flannel
    api_version: v1
    kind: Namespace
    state: present
  become: true

- name: Download Helm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get-helm-3
    mode: '0755'

- name: Install Helm
  ansible.builtin.command: /tmp/get-helm-3
  args:
    creates: /usr/local/bin/helm

- name: Apply namespace with pod-security label
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-flannel
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present
    apply: yes
  become: true

- name: Add Flannel Helm repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/
  become: true

- name: Install Flannel via Helm
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: kube-flannel
    create_namespace: false
    state: present
    wait: true
    wait_timeout: 300s
  become: true

- name: Upload Multus DaemonSet manifest with patched resources to the master node
  copy:
    src: multus-daemonset.yml
    dest: /root/multus-daemonset.yml
    mode: '0644'
  become: true

- name: Install Multus DaemonSet
  kubernetes.core.k8s:
    state: present
    src: /root/multus-daemonset.yml
  become: true

  
- name: Wait for Multus DaemonSet to be ready
  kubernetes.core.k8s_info:
    kind: DaemonSet
    namespace: kube-system
    name: kube-multus-ds
  register: multus_ds_info
  until: multus_ds_info.resources[0].status.desiredNumberScheduled == multus_ds_info.resources[0].status.numberReady
  retries: 20
  delay: 15
  become: true

- name: Ensure Open vSwitch is installed
  apt:
    name: openvswitch-switch
    state: present
    update_cache: yes
  become: true

- name: Create OVS bridges for ovs-cni
  command: "ovs-vsctl --may-exist add-br {{ item }}"
  loop:
    - n2br
    - n3br
    - n4br
  become: true

- name: Apply Cluster-Network-Addons Operator & OVS-CNI
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    kubeconfig: "{{ kubeconfig | default('/etc/kubernetes/admin.conf') }}"
  loop:
    - "https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.89.1/namespace.yaml"
    - "https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.89.1/network-addons-config.crd.yaml"
    - "https://github.com/kubevirt/cluster-network-addons-operator/releases/download/v0.89.1/operator.yaml"
    - "https://gist.githubusercontent.com/niloysh/1f14c473ebc08a18c4b520a868042026/raw/d96f07e241bb18d2f3863423a375510a395be253/network-addons-config.yaml"
  become: false

- name: Wait 10 seconds for cluster-network-addons Ready
  pause:
    seconds: 10