---
# see https://gitlab.eurecom.fr/oai/orchestration/charts/-/blob/oai-gnb-fhi-72/oai-gnb-fhi-72/README.md#prerequisite
- name: RESTART_SR-IOV
  ansible.builtin.meta: noop

- name: Label sopnode-f3 as SR-IOV capable
  kubernetes.core.k8s:
    api_version: v1
    kind: Node
    name: hostvars[groups['ran_node'][0]]
    definition:
      metadata:
        labels:
          feature.node.kubernetes.io/network-sriov.capable: "true"
    state: patched
  delegate_to: "{{ groups['ran_node'][0] }}"   # run from control/master node


- name: Load ran_node vars on controller
  include_vars:
    file: "/home/turletti/xp/post5g-beta/ptp_test/5g_ansible/group_vars/ran_node.yml"
    name: ran_vars
  run_once: true
  delegate_to: localhost

- name: Debug ran_node vars
  debug:
    msg: "ran_node dpdk_interface={{ ran_vars.dpdk_interface | default('NOT DEFINED') }}"
  run_once: true
  
- name: Create SR-IOV Node Policies for C_PLANE
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "{{ ran_vars.sriovResourceNameCplane }}"
        namespace: "{{ ran_vars.sriovNetworkNamespace }}"
      spec:
        resourceName: "{{ ran_vars.sriovResourceNameCplane }}"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 12
        mtu: 9216
        deviceType: vfio-pci
        isRdma: false
        numVfs: 4
        linkType: eth
        nicSelector:
          pfNames: ["{{ ran_vars.dpdk_interface }}"]
          rootDevices: ["{{ ran_vars.dpdk_du_c_plane_mac }}"]

- name: Create SR-IOV Node Policies for U_PLANE
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "{{ ran_vars.sriovResourceNameUplane }}"
        namespace: "{{ ran_vars.sriovNetworkNamespace }}"
      spec:
        resourceName: "{{ ran_vars.sriovResourceNameUplane }}"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 11
        mtu: 9216
        deviceType: vfio-pci
        isRdma: false
        numVfs: 4
        linkType: eth
        nicSelector:
          pfNames: ["{{ ran_vars.dpdk_interface }}"]
          rootDevices: ["{{ ran_vars.dpdk_du_u_plane_mac }}"]

