---
# see https://gitlab.eurecom.fr/oai/orchestration/charts/-/blob/oai-gnb-fhi-72/oai-gnb-fhi-72/README.md#prerequisite
- name: RESTART_SR-IOV
  ansible.builtin.meta: noop

- name: Load ran_node vars on controller
  include_vars:
    file: "/home/turletti/xp/post5g-beta/ptp_test/5g_ansible/group_vars/ran_node.yml"
    name: ran_vars
  run_once: true
  delegate_to: localhost

- name: Label node {{ ran_vars.ran_sopnode }} as SR-IOV capable
  kubernetes.core.k8s:
    api_version: v1
    kind: Node
    name: "{{ ran_vars.ran_sopnode }}"
    definition:
      metadata:
        labels:
          feature.node.kubernetes.io/network-sriov.capable: "true"
          node-role.kubernetes.io/worker: ""
    state: patched
  delegate_to: "{{ groups['core_node'][0] }}"   # run from control/master node


- name: Wait until SR-IOV operator detects NICs on the node
  kubernetes.core.k8s_info:
    api_version: sriovnetwork.openshift.io/v1
    kind: SriovNetworkNodeState
    name: "{{ ran_vars.ran_sopnode }}"
    namespace: "{{ ran_vars.sriovNetworkNamespace }}"
  register: sriov_node_state
  until: >
    sriov_node_state.resources | length > 0 and
    (
      sriov_node_state.resources[0].status.interfaces | default([]) |
      selectattr('name', 'equalto', ran_vars.dpdk_interface_c.split('#')[0]) |
      list | length
    ) > 0
  retries: 20     # give it more time to reconcile
  delay: 10

- name: Create SR-IOV Node Policies for C_PLANE
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "{{ ran_vars.sriovResourceNameCplane }}"
        namespace: "{{ ran_vars.sriovNetworkNamespace }}"
      spec:
        resourceName: "{{ ran_vars.sriovResourceNameCplane }}"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 12
        mtu: 9216
        deviceType: vfio-pci
        isRdma: false
        numVfs: 4
        linkType: eth
        nicSelector:
          pfNames: ["{{ ran_vars.dpdk_interface_c }}"]
          #rootDevices: ["{{ ran_vars.pci_dpdk_interface }}"]

- name: Create SR-IOV Node Policies for U_PLANE
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "{{ ran_vars.sriovResourceNameUplane }}"
        namespace: "{{ ran_vars.sriovNetworkNamespace }}"
      spec:
        resourceName: "{{ ran_vars.sriovResourceNameUplane }}"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 11
        mtu: 9216
        deviceType: vfio-pci
        isRdma: false
        numVfs: 4
        linkType: eth
        nicSelector:
          pfNames: ["{{ ran_vars.dpdk_interface_u }}"]
          #rootDevices: ["{{ ran_vars.pci_dpdk_interface }}"]

- name: Show PFs, VFs, and MTU for RAN NIC 
  shell: |
    NIC={{ ran_vars.dpdk_interface }}
    if [ ! -d /sys/class/net/$NIC ]; then
      echo "NIC $NIC does not exist, skipping"
      exit 0
    fi
    PF_PATH=/sys/class/net/$NIC/device
    PF_PCI=$(basename $(readlink -f $PF_PATH))
    MTU=$(cat /sys/class/net/$NIC/mtu)
    echo "PF: $NIC ($PF_PCI), MTU: $MTU"
    for vf in $PF_PATH/virtfn*; do
      [ -e "$vf" ] || continue
      VF_PCI=$(basename $(readlink -f "$vf"))
      echo "  -> VF: $VF_PCI"
    done
  register: nic_vf_info
  changed_when: false

- name: Display PF, VF, and MTU information
  debug:
    msg: "{{ nic_vf_info.stdout_lines }}"
  

