---
# see https://gitlab.eurecom.fr/oai/orchestration/charts/-/blob/oai-gnb-fhi-72/oai-gnb-fhi-72/README.md#prerequisite
- name: RESTART_SR-IOV
  ansible.builtin.meta: noop

- name: Load ran_node vars on controller
  include_vars:
    file: "/home/turletti/xp/post5g-beta/ptp_test/5g_ansible/group_vars/ran_node.yml"
    name: ran_vars
  run_once: true
  delegate_to: localhost

- name: Label node {{ ran_vars.ran_sopnode }} as SR-IOV capable
  kubernetes.core.k8s:
    api_version: v1
    kind: Node
    name: "{{ ran_vars.ran_sopnode }}"
    definition:
      metadata:
        labels:
          feature.node.kubernetes.io/network-sriov.capable: "true"
          node-role.kubernetes.io/worker: ""
    state: patched
  delegate_to: "{{ groups['core_node'][0] }}"   # run from control/master node

- name: Debug ran_node vars
  debug:
    msg: "ran_node dpdk_interface_c={{ ran_vars.dpdk_interface_c | default('NOT DEFINED') }}"
    msg: "ran_node sriovResourceNameCplane={{ ran_vars.sriovResourceNameCplane | default('NOT DEFINED') }}"
  run_once: true

# sometimes, fails with "denied the request: no supported NIC is selected by the nicSelector in CR ruvfioc"
# try adding 20s delay here...
- name: Wait 20 seconds
  pause:
    seconds: 20

- name: Create SR-IOV Node Policies for C_PLANE
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "{{ ran_vars.sriovResourceNameCplane }}"
        namespace: "{{ ran_vars.sriovNetworkNamespace }}"
      spec:
        resourceName: "{{ ran_vars.sriovResourceNameCplane }}"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 12
        mtu: 9216
        deviceType: vfio-pci
        isRdma: false
        numVfs: 4
        linkType: eth
        nicSelector:
          pfNames: ["{{ ran_vars.dpdk_interface_c }}"]
          #rootDevices: ["{{ ran_vars.pci_dpdk_interface }}"]

- name: Create SR-IOV Node Policies for U_PLANE
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovNetworkNodePolicy
      metadata:
        name: "{{ ran_vars.sriovResourceNameUplane }}"
        namespace: "{{ ran_vars.sriovNetworkNamespace }}"
      spec:
        resourceName: "{{ ran_vars.sriovResourceNameUplane }}"
        nodeSelector:
          feature.node.kubernetes.io/network-sriov.capable: "true"
        priority: 11
        mtu: 9216
        deviceType: vfio-pci
        isRdma: false
        numVfs: 4
        linkType: eth
        nicSelector:
          pfNames: ["{{ ran_vars.dpdk_interface_u }}"]
          #rootDevices: ["{{ ran_vars.pci_dpdk_interface }}"]

