---
 
- name: Ensure iavf module is present
  ansible.builtin.modprobe:
    name: iavf
    state: present

- name: Set maximum ring buffers
  ansible.builtin.command: >
    ethtool -G {{ dpdk_interface }} rx {{ dpdk_max_ring_buffer_size }} tx {{ dpdk_max_ring_buffer_size }}
  changed_when: true

- name: Set MTU on physical interface
  ansible.builtin.command: >
    ip link set {{ dpdk_interface }} mtu {{ dpdk_mtu }}
  changed_when: true

- name: Reset VFs to zero
  ansible.builtin.shell: echo 0 > /sys/class/net/{{ dpdk_interface }}/device/sriov_numvfs
  args:
    executable: /bin/bash
  changed_when: true

- name: Create two VFs
  ansible.builtin.shell: echo 2 > /sys/class/net/{{ dpdk_interface }}/device/sriov_numvfs
  args:
    executable: /bin/bash
  changed_when: true

- name: Configure VF 0
  ansible.builtin.command: >
    ip link set {{ dpdk_interface }} vf 0 mac {{ dpdk_du_u_plane_mac }} vlan {{ dpdk_vlan }} mtu {{ dpdk_mtu }}
  changed_when: true

- name: Configure VF 1
  ansible.builtin.command: >
    ip link set {{ dpdk_interface }} vf 1 mac {{ dpdk_du_c_plane_mac }} vlan {{ dpdk_vlan }} mtu {{ dpdk_mtu }}
  changed_when: true

- name: Unbind U plane VF from kernel driver
  ansible.builtin.command: /usr/local/bin/dpdk-devbind.py --unbind {{ dpdk_u_plane_pci }}
  changed_when: true

- name: Unbind C plane VF from kernel driver
  ansible.builtin.command: /usr/local/bin/dpdk-devbind.py --unbind {{ dpdk_c_plane_pci }}
  changed_when: true

- name: Bind U plane VF to DPDK driver
  ansible.builtin.command: /usr/local/bin/dpdk-devbind.py --bind {{ dpdk_driver }} {{ dpdk_u_plane_pci }}
  changed_when: true

- name: Bind C plane VF to DPDK driver
  ansible.builtin.command: /usr/local/bin/dpdk-devbind.py --bind {{ dpdk_driver }} {{ dpdk_c_plane_pci }}
  changed_when: true


