---
- name: (POS RT) Free any existing allocation for {{ pos_rt_node }}
  ansible.builtin.shell: pos allocations free -k "{{ pos_rt_node }}"

- name: (POS RT) Allocate {{ pos_rt_node }}
  ansible.builtin.shell: pos allocations allocate "{{ pos_rt_node }}"

- name: (POS RT) Set image on {{ pos_rt_node }}
  ansible.builtin.shell: >
    pos node image --user {{ pos_rt_user }} {{ pos_rt_node }} {{ pos_rt_image }}

- name: (POS RT) Set boot parameters on {{ pos_rt_node }}
  ansible.builtin.shell: >
    pos nodes bootparameter {{ pos_rt_node }} {{ pos_rt_boot_parameters | quote }}

- name: (POS RT) Reset {{ pos_rt_node }}
  ansible.builtin.shell: pos nodes reset "{{ pos_rt_node }}"


