---
# Debian/Ubuntu
- name: Install prerequisites (Debian/Ubuntu)
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Remove old Docker repository definitions
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/docker.list
    - /etc/apt/sources.list.d/docker.repo
    - /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Remove legacy Docker keys
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/keyrings/docker.asc
    - /etc/apt/trusted.gpg.d/docker.gpg
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Docker GPG key (Debian/Ubuntu)
  ansible.builtin.shell: |
    install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower }}/gpg \
      | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Add Docker APT repository (Debian/Ubuntu)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Show Docker-related sources after cleanup
  ansible.builtin.shell: grep -R "docker" /etc/apt/sources.list.d/ || true
  register: docker_sources
  changed_when: false
  when: ansible_facts['os_family'] == 'Debian'

- name: Debug Docker sources
  debug:
    msg: "{{ docker_sources.stdout_lines }}"
  when: ansible_facts['os_family'] == 'Debian'

- name: Update APT cache (Debian/Ubuntu)
  apt:
    update_cache: yes
  become: true
  when: ansible_facts['os_family'] == 'Debian'

# RHEL/CentOS/Alma/Rocky
- name: Install prerequisites (RHEL family)
  yum:
    name:
      - dnf-plugins-core
      - curl
      - ca-certificates
    state: present
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Add Docker repo (RHEL family)
  command: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install containerd (RHEL family)
  yum:
    name: containerd.io
    state: present
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

# Common setup (both families)
- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
  become: true

- name: Generate default containerd config
  command: containerd config default
  register: containerd_cfg
  changed_when: false
  become: true

- name: Write config.toml
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_cfg.stdout }}"
  become: true

- name: Enable systemd-cgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  become: true

- name: Switch snapshotter to native
  replace:
    path: /etc/containerd/config.toml
    regexp: 'snapshotter = "overlayfs"'
    replace: 'snapshotter = "native"'
  become: true

- name: Restart & enable containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted
  become: true
