---
- hosts: faraday
  gather_facts: false
  tasks:
    - name: Cleanup R2Lab
      include_role:
        name: r2lab/cleanup

    - name: Setup UEs on R2Lab
      include_role:
        name: r2lab/ue/setup

    - name: Stop all UEs previous connections in parallel
      block:
        - name: Stop UE
          include_role:
            name: r2lab/ue/stop
          vars:
            ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"
      loop_control:
        label: "{{ item }}"
      async: 1800
      poll: 0
      ignore_errors: true

    - name: Power ON RRU
      include_role:
        name: r2lab/rru

    - name: Mark Block2 as done
      file:
        path: "/home/turletti/xp/post5g-beta/5g_ansible/playbooks/block2.done"
        state: touch

