---
- name: Configure CPU and tuned profile on Ubuntu 22.04
  hosts: sopnodes
  tasks:
    - name: Install cpufrequtils and tuned
      apt:
        name:
          - cpufrequtils
          - tuned
        state: present
        update_cache: yes

    - name: Install cpupower utility
      package:
        name:
          - linux-tools-common
          - linux-tools-{{ ansible_kernel }}
          - cpufrequtils
          - tuned-utils
        state: present

    - name: Set CPU governor to performance on every core
      shell: bash -c 'for ((i=0;i<$(nproc);i++)); do cpufreq-set -c $i -r -g performance; done'
      ignore_errors: true
      when: inventory_hostname != "sopnode-f3"

    - name: Apply sysctl tuning parameters
      sysctl:
        name: "{{ item.key }}"
        value: "{{ item.val }}"
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - { key: net.core.rmem_default,        val: '134217728' }
        - { key: net.core.rmem_max,            val: '134217728' }
        - { key: net.core.wmem_default,        val: '134217728' }
        - { key: net.core.wmem_max,            val: '134217728' }
        - { key: net.core.netdev_max_backlog,  val: '5000'      }
        - { key: net.core.optmem_max,          val: '524288'    }
        - { key: kernel.sched_rt_runtime_us,   val: '-1'        }
        - { key: kernel.timer_migration,       val: '0'         }

    - name: Set tuned profile to throughput-performance
      command: tuned-adm profile throughput-performance
      register: tuned_profile
      changed_when: "'Current active profile: throughput-performance' not in tuned_profile.stdout"

    - name: Show current tuned profile
      debug:
        msg: "{{ tuned_profile.stdout }}"

    - name: Check if hyperthreading is disabled
      shell: |
        physical=$(lscpu | awk '/^Core\(s\) per socket:/ {cores=$4}
                                 /^Socket\(s\):/ {sockets=$2}
                                 END {print cores * sockets}')
        logical=$(lscpu | awk '/^CPU\(s\):/ {print $2}')
        if [ "$logical" -eq "$physical" ]; then
          echo "Hyperthreading is disabled"
        else
          echo "Hyperthreading is enabled"
        fi
      register: ht_check
      changed_when: false
      failed_when: false

    - name: Show hyperthreading status
      debug:
        msg: "{{ ht_check.stdout }}"

