---
- name: Install cpufrequtils and tuned
  apt:
    name:
      - cpufrequtils
    state: present
    update_cache: yes
  become: true

- name: Install cpupower utility
  become: true
  package:
    name:
      - linux-tools-common   # Debian/Ubuntu only
      - linux-tools-{{ ansible_kernel }}   # Debian/Ubuntu kernel-specific tools
      - cpufrequtils
      - tuned tuned-utils
    state: present

- name: Set CPU governor to performance on every core
  shell: bash -c 'for ((i=0;i<$(nproc);i++)); do cpufreq-set -c $i -r -g performance; done'
  become: true
  ignore_errors: true
  when: inventory_hostname != "sopnode-f3"

- name: Apply sysctl tuning parameters
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.val }}"
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - { key: net.core.rmem_default,        val: '134217728' }
    - { key: net.core.rmem_max,            val: '134217728' }
    - { key: net.core.wmem_default,        val: '134217728' }
    - { key: net.core.wmem_max,            val: '134217728' }
    - { key: net.core.netdev_max_backlog,  val: '5000'      }
    - { key: net.core.optmem_max,          val: '524288'    }
    - { key: kernel.sched_rt_runtime_us,   val: '-1'        }
    - { key: kernel.timer_migration,       val: '0'         }
  become: true

- name: Set tuned profile to throughput-performance
  ansible.builtin.command: tuned-adm profile throughput-performance
  register: tuned_profile
  changed_when: "'Current active profile: throughput-performance' not in tuned_profile.stdout"

- name: Show current tuned profile
  ansible.builtin.debug:
    msg: "{{ tuned_profile.stdout }}"

- name: Check if hyperthreading is disabled
  shell: |
    # Count physical cores vs logical CPUs
    physical=$(lscpu | awk '/^Core\(s\) per socket:/ {cores=$4}
                               /^Socket\(s\):/ {sockets=$2}
                               END {print cores * sockets}')
    logical=$(lscpu | awk '/^CPU\(s\):/ {print $2}')
    if [ "$logical" -eq "$physical" ]; then
      echo "Hyperthreading is disabled"
      exit 0
    else
      echo "Hyperthreading is enabled"
      exit 1
    fi
  register: ht_check
  changed_when: false
  failed_when: ht_check.rc != 0
  when: inventory_hostname = "sopnode-f3"

- name: Show hyperthreading status
  debug:
    msg: "{{ ht_check.stdout }}"
  when: inventory_hostname = "sopnode-f3"